### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by xlith** [johnnybenson/package-json-versioned-action#140]
First of all, thank you for the project. 

It seems GitHub deprecated the use of Node 12.
Here is the related blog page:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Can you please update the repo?

**Comment by johnnybenson** [comment]
here you go
https://github.com/johnnybenson/package-json-versioned-action/releases/tag/v1.0.7
